[package]
name = "oben"
version = "0.1.0"
authors = ["at-robins <30956028+at-robins@users.noreply.github.com>"]
edition = "2021"

[dependencies]
approx = "0.4"
bitvec = {version = "0.17.4", features = ["serde"]}
rand = "0.7.3"
rand_distr = "0.2.2"
serde = "1.0"
serde_json = "1.0"
uuid = {version = "0.8", features = ["serde", "v1"]}
rayon = "1.3"
rmp-serde = "0.14.3"
