[package]
name = "oben"
version = "0.1.0"
authors = ["at-robins <30956028+at-robins@users.noreply.github.com>"]
edition = "2018"

[dependencies]
bitvec = {version = "0.17.4", features = ["serde"]}
rand = "0.7.3"
serde = "1.0"
serde_json = "1.0"
uuid = {version = "0.8", features = ["serde", "v1"]}
